Repository alicevision/Meshroom, pull requests merged in 2019-09, with the labels that each got.

#564 Visual interface for node statistics
  meshroom/core/node.py
  meshroom/core/stats.py
  meshroom/ui/qml/Charts/ChartViewCheckBox.qml
  meshroom/ui/qml/Charts/ChartViewLegend.qml
  meshroom/ui/qml/Charts/qmldir
  meshroom/ui/qml/GraphEditor/NodeLog.qml
  meshroom/ui/qml/GraphEditor/StatViewer.qml
  requirements.txt
Labels: UI, new feature, type:pr

#584 Add option to include 'unknown' feature types in ConvertSfMFormat
  meshroom/nodes/aliceVision/ConvertSfMFormat.py
Labels: type:pr

#632 Improve command line arguments
  bin/meshroom_photogrammetry
  meshroom/core/__init__.py
  meshroom/core/graph.py
  meshroom/multiview.py
  meshroom/ui/app.py
  meshroom/ui/graph.py
  meshroom/ui/reconstruction.py
Labels: cli, type:enhancement, type:pr
