Repository alicevision/Meshroom, pull requests merged in 2020-12, with the labels that each got.

#612 Improve Graph Editor UX
  bin/meshroom_compute
  bin/meshroom_photogrammetry
  bin/meshroom_submit
  meshroom/__init__.py
  meshroom/common/PySignal.py
  meshroom/common/core.py
  meshroom/common/qt.py
  meshroom/core/attribute.py
  meshroom/core/graph.py
  meshroom/core/node.py
  meshroom/core/taskManager.py
  meshroom/nodes/aliceVision/CameraInit.py
  meshroom/nodes/aliceVision/DepthMap.py
  meshroom/nodes/aliceVision/DepthMapFilter.py
  meshroom/nodes/aliceVision/FeatureExtraction.py
  meshroom/nodes/aliceVision/FeatureMatching.py
  meshroom/nodes/aliceVision/ImageMatching.py
  meshroom/nodes/aliceVision/MeshFiltering.py
  meshroom/nodes/aliceVision/Meshing.py
  meshroom/nodes/aliceVision/PrepareDenseScene.py
  meshroom/nodes/aliceVision/StructureFromMotion.py
  meshroom/nodes/aliceVision/Texturing.py
  meshroom/ui/app.py
  meshroom/ui/commands.py
  meshroom/ui/graph.py
  meshroom/ui/qml/Controls/TabPanel.qml
  meshroom/ui/qml/Controls/qmldir
  meshroom/ui/qml/GraphEditor/AttributePin.qml
  meshroom/ui/qml/GraphEditor/Edge.qml
  meshroom/ui/qml/GraphEditor/GraphEditor.qml
  meshroom/ui/qml/GraphEditor/Node.qml
  meshroom/ui/qml/GraphEditor/NodeChunks.qml
  meshroom/ui/qml/GraphEditor/TaskManager.qml
  meshroom/ui/qml/GraphEditor/common.js
  meshroom/ui/qml/GraphEditor/qmldir
  meshroom/ui/qml/Utils/Colors.qml
  meshroom/ui/qml/Utils/errorHandler.js
  meshroom/ui/qml/Utils/qmldir
  meshroom/ui/qml/main.qml
  meshroom/ui/reconstruction.py
  tests/test_graph.py
Labels: UI, type:enhancement, type:pr

#390 [nodes] New node `LightingEstimation`
  meshroom/nodes/aliceVision/LightingEstimation.py
  meshroom/ui/qml/Viewer3D/MaterialSwitcher.qml
  meshroom/ui/qml/Viewer3D/Materials/SphericalHarmonicsEffect.qml
  meshroom/ui/qml/Viewer3D/Materials/SphericalHarmonicsMaterial.qml
  meshroom/ui/qml/Viewer3D/Materials/shaders/SphericalHarmonics.frag
  meshroom/ui/qml/Viewer3D/Materials/shaders/SphericalHarmonics.vert
  meshroom/ui/qml/Viewer3D/Viewer3D.qml
  meshroom/ui/qml/Viewer3D/Viewer3DSettings.qml
Labels: do not close, review, scope:AliceVision, type:pr

#1190 Update LdrToHdrSampling.py
  meshroom/nodes/aliceVision/LdrToHdrSampling.py
Labels: prio:minor
