Repository alicevision/Meshroom, pull requests merged in 2021-07, with the labels that each got.

#1464 Create Split360Images Node
  meshroom/nodes/aliceVision/Split360Images.py
Labels: review

#1477 [nodes] add gps option to SfMTransform
  meshroom/nodes/aliceVision/SfMTransform.py
Labels: type:enhancement

#1180 Integration of AprilTag library according to issue #1179 and AliceVision pull request #950
  meshroom/nodes/aliceVision/ConvertSfMFormat.py
  meshroom/nodes/aliceVision/FeatureExtraction.py
  meshroom/nodes/aliceVision/FeatureMatching.py
  meshroom/nodes/aliceVision/SfMTransform.py
  meshroom/nodes/aliceVision/StructureFromMotion.py
Labels: do not close, new feature
