Repository alicevision/Meshroom, pull requests merged in 2023-07, with the labels that each got.

#2079 Support pixel aspect ratio (no UI)
  meshroom/nodes/aliceVision/CameraInit.py
  meshroom/nodes/blender/scripts/preview.py
Labels: Blender

#2094 [core] Add brackets option for GroupAttribute
  meshroom/core/attribute.py
  meshroom/core/desc.py
Labels: review

#2072 Advanced pixelwise merging
  meshroom/nodes/aliceVision/LdrToHdrMerge.py
Labels: invalidate:node

#2090 Set `ALICEVISION_SEMANTIC_SEGMENTATION_MODEL` variable during the initialisation
  INSTALL.md
  meshroom/__init__.py
Labels: scope:build, scope:doc

#2107 QML: Fix minor coercion error and warning
  meshroom/ui/qml/Utils/SortFilterDelegateModel.qml
  meshroom/ui/qml/Viewer/Viewer2D.qml
Labels: bugfix

#1989 [ui] 2D viewer: image sequence player
  meshroom/ui/qml/Viewer/FloatImage.qml
  meshroom/ui/qml/Viewer/PanoramaViewer.qml
  meshroom/ui/qml/Viewer/SequencePlayer.qml
  meshroom/ui/qml/Viewer/Viewer2D.qml
  meshroom/ui/qml/WorkspaceView.qml
  meshroom/ui/reconstruction.py
Labels: feature, UI

#2133 [nodes] new exportLevels option in PanoramaPostProcessing
  meshroom/nodes/aliceVision/PanoramaPostProcessing.py
  meshroom/pipelines/panoramaFisheyeHdr.mg
  meshroom/pipelines/panoramaHdr.mg
Labels: 360/fisheye, invalidate:node
