Repository alicevision/Meshroom, pull requests merged in 2023-08, with the labels that each got.

#2131 [build] Remove references to QmlAlembic in the build process
  CMakeLists.txt
  COPYING.md
  INSTALL.md
  docker/Dockerfile_centos
  docker/Dockerfile_ubuntu
  docker/Dockerfile_ubuntu_deps
Labels: scope:build

#2125 [ui] GraphEditor: Minor UI changes
  meshroom/core/node.py
  meshroom/ui/qml/GraphEditor/ChunksListView.qml
  meshroom/ui/qml/GraphEditor/CompatibilityManager.qml
  meshroom/ui/qml/GraphEditor/NodeEditor.qml
Labels: UI

#2137 [bin] meshroom_batch: support multiple init nodes
  bin/meshroom_batch
Labels: feature

#2143 [nodes] HDR Fusion: Fix bracket detection
  meshroom/nodes/aliceVision/LdrToHdrCalibration.py
  meshroom/nodes/aliceVision/LdrToHdrMerge.py
  meshroom/nodes/aliceVision/LdrToHdrSampling.py
Labels: bugfix

#2127 [core] Preserve edges by recreating all the nodes during UID evaluation
  meshroom/core/graph.py
Labels: bugfix

#2160 [UI] fix resize of horizontal splitview
  meshroom/ui/qml/WorkspaceView.qml
Labels: UI

#2141 AttributeEditor: Flag attributes with invalid values
  meshroom/core/attribute.py
  meshroom/core/desc.py
  meshroom/nodes/aliceVision/LdrToHdrCalibration.py
  meshroom/nodes/aliceVision/LdrToHdrMerge.py
  meshroom/nodes/aliceVision/LdrToHdrSampling.py
  meshroom/ui/qml/GraphEditor/AttributeItemDelegate.qml
  meshroom/ui/qml/MaterialIcons/MaterialIcons.qml
Labels: UI

#2167 [nodes] KeyframeSelection: Add support for masks
  meshroom/nodes/aliceVision/KeyframeSelection.py
  meshroom/pipelines/cameraTracking.mg
  meshroom/pipelines/photogrammetryAndCameraTracking.mg
Labels: invalidate:node
