Repository alicevision/Meshroom, pull requests merged in 2023-11, with the labels that each got.

#2238 [pipelines] PhotogAndCamTrack: Disable automatic alignment in SfM
  meshroom/pipelines/photogrammetryAndCameraTracking.mg
Labels: invalidate:node

#2236 Automatic reorientation
  meshroom/nodes/aliceVision/ImageProcessing.py
Labels: invalidate:node

#2232 [pipelines] Photogrammetry Draft: Add a `PrepareDenseScene` node to the template
  meshroom/pipelines/photogrammetryDraft.mg
Labels: bugfix

#2235 [Viewer3D] Add slider to display cameras based on their resection IDs
  meshroom/ui/qml/Controls/ExpandableGroup.qml
  meshroom/ui/qml/Controls/qmldir
  meshroom/ui/qml/MaterialIcons/MaterialIcons.qml
  meshroom/ui/qml/Viewer3D/Inspector3D.qml
  meshroom/ui/qml/Viewer3D/MediaLibrary.qml
  meshroom/ui/qml/Viewer3D/MediaLoader.qml
  meshroom/ui/qml/Viewer3D/MediaLoaderEntity.qml
  meshroom/ui/qml/Viewer3D/SfmDataLoader.qml
  meshroom/ui/qml/Viewer3D/Viewer3DSettings.qml
Labels: UI

#2258 [core] Only update the running chunk to `STOPPED` when stopping computations
  meshroom/core/node.py
Labels: bugfix
