Repository alicevision/Meshroom, pull requests merged in 2023-10, with the labels that each got.

#2171 [nodes] new IntrinsicsCalibration node
  meshroom/nodes/aliceVision/CheckerboardCalibration.py
Labels: feature

#2221 [ui] ImageGallery: Add "Remove All Images" menu to clear all images
  meshroom/ui/commands.py
  meshroom/ui/graph.py
  meshroom/ui/qml/ImageGallery/ImageDelegate.qml
  meshroom/ui/qml/ImageGallery/ImageGallery.qml
  meshroom/ui/qml/WorkspaceView.qml
  meshroom/ui/qml/main.qml
Labels: UI

#2219 Input color space setting
  meshroom/nodes/aliceVision/ImageProcessing.py
Labels: invalidate:node

#2145 [ui] Preserve last `CameraInit` index when updating the CameraInits list
  meshroom/ui/qml/ImageGallery/ImageGallery.qml
  meshroom/ui/reconstruction.py
Labels: bugfix, UI

#2230 [ui] Don't load a node's output in the 3DViewer if it has no 3D output
  meshroom/ui/qml/main.qml
Labels: bugfix

#2227 [pipelines] CamTrack: Update default params for keyframes SfM
  meshroom/pipelines/cameraTracking.mg
  meshroom/pipelines/cameraTrackingWithoutCalibration.mg
  meshroom/pipelines/photogrammetryAndCameraTracking.mg
Labels: invalidate:node
