Repository alicevision/Meshroom, pull requests merged in 2023-04, with the labels that each got.

#1978 Add rec709 color space options
  meshroom/nodes/aliceVision/ImageProcessing.py
  meshroom/nodes/aliceVision/PanoramaPostProcessing.py
  meshroom/nodes/aliceVision/Texturing.py
Labels: new feature

#1990 [doc] RELEASING: Add example command to generate the release note
  RELEASING.md
Labels: scope:doc

#1996 [core] Stats: Retrieve and set the GPU name if it is found
  meshroom/core/stats.py
Labels: bugfix
