Repository alicevision/Meshroom, pull requests merged in 2023-12, with the labels that each got.

#2262 Release 2023.3.0
  CHANGES.md
  RELEASING.md
  meshroom/__init__.py
  meshroom/pipelines/cameraTracking.mg
  meshroom/pipelines/cameraTrackingWithoutCalibration.mg
  meshroom/pipelines/distortionCalibration.mg
  meshroom/pipelines/hdrFusion.mg
  meshroom/pipelines/nodalCameraTracking.mg
  meshroom/pipelines/panoramaFisheyeHdr.mg
  meshroom/pipelines/panoramaHdr.mg
  meshroom/pipelines/photogrammetry.mg
  meshroom/pipelines/photogrammetryAndCameraTracking.mg
  meshroom/pipelines/photogrammetryDraft.mg
  meshroom/pipelines/stereoPhotometry.mg
Labels: release

#2268 Start Development 2024.1.0
  meshroom/__init__.py
Labels: release

#2276 [nodes] ExportDistortion: Option to export lens grid undistorted
  meshroom/nodes/aliceVision/ExportDistortion.py
Labels: feature

#2277 Fix duplicated icon in MaterialIcons
  meshroom/ui/qml/MaterialIcons/MaterialIcons.qml
Labels: bugfix
