Repository alicevision/Meshroom, pull requests merged in 2023-09, with the labels that each got.

#2170 [blender] apply masks to scene preview
  meshroom/nodes/blender/ScenePreview.py
  meshroom/nodes/blender/scripts/preview.py
  meshroom/pipelines/cameraTracking.mg
  meshroom/pipelines/photogrammetryAndCameraTracking.mg
Labels: Blender, invalidate:node

#2173 Multiple UI Improvements
  meshroom/core/attribute.py
  meshroom/ui/qml/GraphEditor/AttributeEditor.qml
  meshroom/ui/qml/GraphEditor/AttributeItemDelegate.qml
  meshroom/ui/qml/GraphEditor/GraphEditor.qml
  meshroom/ui/qml/GraphEditor/GraphEditorSettings.qml
  meshroom/ui/qml/GraphEditor/NodeEditor.qml
  meshroom/ui/qml/Viewer3D/Inspector3D.qml
Labels: UI

#2148 [ui] FloatImageViewer: adapt resolution to zoom
  meshroom/ui/qml/Viewer/FloatImage.qml
  meshroom/ui/qml/Viewer/SequencePlayer.qml
  meshroom/ui/qml/Viewer/Viewer2D.qml
Labels: UI

#2188 [bin] `meshroom_batch`: Fix input parsing for Windows
  bin/meshroom_batch
Labels: bugfix

#2193 [nodes] PanoramaPostProcessing: Add attributes to change the outputs' names
  meshroom/nodes/aliceVision/PanoramaPostProcessing.py
  meshroom/pipelines/panoramaFisheyeHdr.mg
  meshroom/pipelines/panoramaHdr.mg
Labels: invalidate:node

#2195 [nodes] ImageSegmentation: increase GPU requirements
  meshroom/nodes/aliceVision/ImageSegmentation.py
Labels: bugfix

#2180 [ui] ImageGallery: Disable "Visualize HDR" button after clearing images
  meshroom/ui/qml/ImageGallery/ImageGallery.qml
Labels: bugfix, UI

#2190 [ui] Check for the existence of the `poses` key in SfM JSON files before accessing it
  meshroom/ui/reconstruction.py
Labels: bugfix

#2196 [nodes] Meshing: expose minVis param
  meshroom/nodes/aliceVision/Meshing.py
Labels: invalidate:node

#2202 [nodes] CameraInit: fix tooltip focal is in mm
  meshroom/nodes/aliceVision/CameraInit.py
Labels: bugfix

#2199 [nodes] StructureFromMotion: Automatic alignment of the 3D reconstruction
  meshroom/nodes/aliceVision/StructureFromMotion.py
Labels: feature, invalidate:node

#2207 [pipelines] Rename Nodal Tracking to Nodal Camera Tracking
  meshroom/pipelines/nodalCameraTracking.mg
Labels: prio:minor
