Repository alicevision/Meshroom, pull requests merged in 2024-07, with the labels that each got.

#2453 [core] Forward the onAttributeChanged notification to all linked attributes
  meshroom/core/attribute.py
  meshroom/core/node.py
Labels: feature

#2454 [ui] Graph: Connect all chunks when setting a graph for the first time
  meshroom/ui/graph.py
Labels: bugfix

#2455 [core] Exclude edges from `InputNode` nodes in `dfsToProcess`
  meshroom/core/graph.py
  meshroom/core/node.py
Labels: bugfix

#2456 Add a Python ScriptEditor in the GraphEditor tab
  meshroom/__init__.py
  meshroom/ui/app.py
  meshroom/ui/components/scriptEditor.py
  meshroom/ui/qml/GraphEditor/ScriptEditor.qml
  meshroom/ui/qml/GraphEditor/qmldir
  meshroom/ui/qml/main.qml
Labels: feature

#2446 add 3de undistortion models
  meshroom/nodes/aliceVision/CameraInit.py
  meshroom/nodes/aliceVision/DistortionCalibration.py
  meshroom/nodes/aliceVision/ExportDistortion.py
  meshroom/pipelines/cameraTracking.mg
  meshroom/pipelines/cameraTrackingWithoutCalibration.mg
  meshroom/pipelines/distortionCalibration.mg
  meshroom/pipelines/hdrFusion.mg
  meshroom/pipelines/nodalCameraTracking.mg
  meshroom/pipelines/nodalCameraTrackingWithoutCalibration.mg
  meshroom/pipelines/panoramaFisheyeHdr.mg
  meshroom/pipelines/panoramaHdr.mg
  meshroom/pipelines/photogrammetry.mg
  meshroom/pipelines/photogrammetryAndCameraTracking.mg
  meshroom/pipelines/photogrammetryDraft.mg
  meshroom/pipelines/stereoPhotometry.mg
Labels: feature

#2445 [ui] Sequence Player UI Modifications
  meshroom/ui/qml/Utils/format.js
  meshroom/ui/qml/Viewer/SequencePlayer.qml
  meshroom/ui/qml/Viewer/Viewer2D.qml
Labels: UI

#2469 [core] Values of ChoiceParam should be a list, Error message added for initialisation
  meshroom/core/desc.py
Labels: bugfix

#2465 [nodes] SphereDetection: Increase max value for `sphereRadius`
  meshroom/nodes/aliceVision/SphereDetection.py
Labels: bugfix

#2470 Some fixes for dynamic output attributes
  bin/meshroom_compute
  meshroom/core/node.py
  meshroom/ui/graph.py
  meshroom/ui/qml/GraphEditor/AttributeItemDelegate.qml
Labels: bugfix

#2472 [Viewer] Current frame for Sequence should not be set during changes of Image Gallery
  meshroom/ui/qml/Viewer/Viewer2D.qml
Labels: UI

#2471 [ui] Fix local computation of subgraphs for unsaved projects
  meshroom/ui/qml/main.qml
Labels: bugfix

#2474 [ui] Fix Camera Init Group Index should stay the same at adding or removing CameraInit events
  meshroom/ui/reconstruction.py
Labels: bugfix

#2480 [Viewer2D] Only reset index of currentFrame if the currentFrame is after max of frameRange
  meshroom/ui/qml/Viewer/Viewer2D.qml
Labels: bugfix

#2476 [ui] setSfm only depends on nodes with category "sfm" and CameraInit should be set only if it is different from the current one
  meshroom/ui/reconstruction.py
Labels: bugfix

#2482 [GraphEditor] AttributeItemDelegate: Return valid component for `PushButton`
  meshroom/ui/qml/GraphEditor/AttributeItemDelegate.qml
Labels: bugfix

#2483 [ui] Add project to recent projects when dropping a file
  meshroom/ui/qml/WorkspaceView.qml
  meshroom/ui/qml/main.qml
  meshroom/ui/reconstruction.py
Labels: UI
