Repository alicevision/Meshroom, pull requests merged in 2024-08, with the labels that each got.

#2492 added env var for ci
  .github/workflows/continuous-integration.yml
Labels: ci

#2487 Initialize `core` plugins at different moments
  bin/meshroom_batch
  meshroom/core/__init__.py
  meshroom/ui/app.py
Labels: bugfix

#2494 [GraphEditor] Base `ChoiceParam` model on attribute instead of description
  meshroom/ui/qml/GraphEditor/AttributeItemDelegate.qml
Labels: feature

#2500 [core] Catch exception for calls to optional descriptor method on node creation
  meshroom/core/node.py
Labels: bugfix

#2507 [GraphEditor] Improve visibility of chunks in progress bar
  meshroom/ui/qml/GraphEditor/NodeChunks.qml
  meshroom/ui/qml/main.qml
Labels: UI

#2502 [ui] Improve sequence display
  meshroom/ui/components/filepath.py
  meshroom/ui/qml/Viewer/Viewer2D.qml
Labels: bugfix

#2511 [ui] GraphEditor.newNodeMenu: fix unstable menu height
  meshroom/ui/qml/GraphEditor/GraphEditor.qml
Labels: bugfix

#2452 First Homepage
  meshroom/core/graph.py
  meshroom/ui/app.py
  meshroom/ui/components/thumbnail.py
  meshroom/ui/graph.py
  meshroom/ui/img/MIKROS_TG.png
  meshroom/ui/img/MILL_TG.png
  meshroom/ui/img/MPC_TG.png
  meshroom/ui/img/TechnicolorGames_TG.png
  meshroom/ui/img/meshroom-anim-once.gif
  meshroom/ui/img/technicolor-group_rgb_primary_col-rev.png
  meshroom/ui/qml/Application.qml
  meshroom/ui/qml/Controls/TabPanel.qml
  meshroom/ui/qml/GraphEditor/GraphEditor.qml
  meshroom/ui/qml/Homepage.qml
  meshroom/ui/qml/MaterialIcons/MaterialToolLabelButton.qml
  meshroom/ui/qml/main.qml
  meshroom/ui/reconstruction.py
Labels: UI, majorFeature

#2515 [nodes] ApplyCalibration: Add option to use a Lens calibration file from 3dequalizer in json
  meshroom/nodes/aliceVision/ApplyCalibration.py
Labels: feature

#2518 [ui] Improve command line help message
  bin/meshroom_batch
  meshroom/ui/app.py
Labels: feature
