Repository alicevision/Meshroom, pull requests merged in 2024-04, with the labels that each got.

#2358 [ui] Add new FilterComboBox for ChoiceParam attributes
  meshroom/nodes/aliceVision/Texturing.py
  meshroom/ui/qml/Controls/FilterComboBox.qml
  meshroom/ui/qml/Controls/qmldir
  meshroom/ui/qml/GraphEditor/AttributeItemDelegate.qml
Labels: UI

#2365 Lidar nodes
  meshroom/nodes/aliceVision/LidarDecimating.py
  meshroom/nodes/aliceVision/LidarMerging.py
  meshroom/nodes/aliceVision/LidarMeshing.py
Labels: feature

#2376 [ui] Scroll available in FilterComboBox
  meshroom/ui/qml/Controls/FilterComboBox.qml
Labels: bugfix, UI

#2377 [Viewer] fix lens distortion viewer status when switching between projects
  meshroom/ui/qml/Viewer/Viewer2D.qml
Labels: bugfix

#2362 [ui] Sequence Player UX improvements (fps, slider, frame)
  meshroom/ui/qml/Viewer/SequencePlayer.qml
Labels: UI
