Repository alicevision/Meshroom, pull requests merged in 2024-05, with the labels that each got.

#2391 [ui] Bounding Box are usable in other nodes, not only Meshing
  meshroom/ui/qml/Viewer3D/MediaLibrary.qml
  meshroom/ui/qml/main.qml
Labels: UI

#2399 [ui] Cut option available in GraphEditor
  meshroom/ui/qml/GraphEditor/GraphEditor.qml
  meshroom/ui/qml/main.qml
Labels: UI

#2388 SequencePlayer: Forbid "selecting" an invalid frame number
  meshroom/ui/qml/Viewer/SequencePlayer.qml
Labels: bugfix, UI

#2385 Viewer3D: Adjust bounding-box by moving faces
  meshroom/ui/qml/Viewer3D/TransformGizmo.qml
Labels: UI

#2384 [GraphEditor] Internal Custom Color Picker disabled when node is locked
  meshroom/ui/qml/GraphEditor/AttributeItemDelegate.qml
Labels: UI

#2389 [ui] Prevent Feature Points to display on external images
  meshroom/ui/qml/Viewer/Viewer2D.qml
Labels: bugfix

#2401 [ui] Selected node header set to base color
  meshroom/ui/qml/GraphEditor/Node.qml
Labels: UI

#2366 [ui] Right click on text element in AttributeEditor open Copy/Paste menu
  meshroom/ui/qml/GraphEditor/AttributeItemDelegate.qml
Labels: UI

#2386 [ui] Fix BoundingBox visibility icon because of mapping name
  meshroom/ui/qml/Viewer3D/Inspector3D.qml
Labels: UI

#2413 [ui] Viewer2D: Display lighting circle with auto detected sphere
  meshroom/ui/qml/Viewer/Viewer2D.qml
Labels: feature, type:enhancement, review

#2398 [ui] Use ExportAnimatedCamera output for image overlay in Viewer3D
  meshroom/nodes/aliceVision/ExportAnimatedCamera.py
  meshroom/nodes/aliceVision/ImageSegmentation.py
  meshroom/nodes/blender/ScenePreview.py
  meshroom/ui/components/filepath.py
  meshroom/ui/qml/Viewer/Viewer2D.qml
  meshroom/ui/reconstruction.py
Labels: UI
