Repository alicevision/Meshroom, pull requests merged in 2024-09, with the labels that each got.

#2520 Homepage Quick Adjustments
  meshroom/ui/img/MIKROS_TG.png
  meshroom/ui/img/MILL_TG.png
  meshroom/ui/img/MPC_TG.png
  meshroom/ui/img/TechnicolorGames_TG.png
  meshroom/ui/img/technicolor-group_rgb_primary_col-rev.png
  meshroom/ui/qml/Homepage.qml
Labels: UI

#2521 [ui] Add proper distinction between the main window and the application
  meshroom/ui/qml/Application.qml
  meshroom/ui/qml/WorkspaceView.qml
  meshroom/ui/qml/main.qml
Labels: bugfix

#2504 First version of For Loop implementation
  meshroom/core/attribute.py
  meshroom/ui/graph.py
  meshroom/ui/qml/Controls/IntSelector.qml
  meshroom/ui/qml/Controls/qmldir
  meshroom/ui/qml/GraphEditor/AttributePin.qml
  meshroom/ui/qml/GraphEditor/Edge.qml
  meshroom/ui/qml/GraphEditor/GraphEditor.qml
  meshroom/ui/qml/GraphEditor/Node.qml
  meshroom/ui/qml/GraphEditor/TaskManager.qml
  meshroom/ui/qml/MaterialIcons/MaterialToolLabel.qml
  meshroom/ui/qml/Viewer/SequencePlayer.qml
Labels: majorFeature

#2519 [ui] Fix function evaluations in invalid QML context and minor fixes
  meshroom/ui/qml/Application.qml
  meshroom/ui/qml/GraphEditor/AttributePin.qml
  meshroom/ui/qml/GraphEditor/GraphEditor.qml
  meshroom/ui/qml/GraphEditor/Node.qml
  meshroom/ui/qml/Viewer3D/MediaLibrary.qml
  meshroom/ui/qml/main.qml
Labels: bugfix

#2243 [Photometric Stereo] MultiView fusion in Texturing
  meshroom/nodes/aliceVision/LightingCalibration.py
  meshroom/nodes/aliceVision/NormalIntegration.py
  meshroom/nodes/aliceVision/PhotometricStereo.py
  meshroom/nodes/aliceVision/SphereDetection.py
  meshroom/nodes/aliceVision/Texturing.py
  meshroom/pipelines/photometricStereo.mg
  meshroom/ui/qml/Viewer/Viewer2D.qml
  start.sh
Labels: feature, invalidate:node

#2527 [AttributePin] Add tooltip to display type of attribute
  meshroom/ui/qml/GraphEditor/AttributeItemDelegate.qml
  meshroom/ui/qml/GraphEditor/AttributePin.qml
Labels: UI

#2526 [ui] Fix click on Category in Node Menu to keep the nodes displayed
  meshroom/ui/qml/GraphEditor/GraphEditor.qml
Labels: UI

#2528 [core/ui] "Exposed" property added to attributeDesc
  meshroom/core/desc.py
  meshroom/ui/qml/GraphEditor/Node.qml
Labels: UI

#2531 UI Changes
  meshroom/nodes/aliceVision/ConvertSfMFormat.py
  meshroom/nodes/aliceVision/FeatureExtraction.py
  meshroom/nodes/aliceVision/FeatureMatching.py
  meshroom/nodes/aliceVision/ImageMatching.py
  meshroom/nodes/aliceVision/ImageMatchingMultiSfM.py
  meshroom/nodes/aliceVision/LdrToHdrCalibration.py
  meshroom/nodes/aliceVision/LdrToHdrMerge.py
  meshroom/nodes/aliceVision/LdrToHdrSampling.py
  meshroom/nodes/aliceVision/PanoramaCompositing.py
  meshroom/nodes/aliceVision/PanoramaEstimation.py
  meshroom/nodes/aliceVision/PanoramaMerging.py
  meshroom/nodes/aliceVision/SfMTriangulation.py
  meshroom/nodes/aliceVision/StructureFromMotion.py
  meshroom/nodes/aliceVision/TracksBuilding.py
  meshroom/ui/qml/Application.qml
  meshroom/ui/qml/GraphEditor/AttributeItemDelegate.qml
Labels: UI

#2506 Fix Several Compatibility Nodes Operations
  meshroom/core/graph.py
  meshroom/core/taskManager.py
  meshroom/ui/qml/GraphEditor/GraphEditor.qml
Labels: bugfix

#2532 [AttributeItemDelegate] Position the attribute description tooltip
  meshroom/ui/qml/GraphEditor/AttributeItemDelegate.qml
  meshroom/ui/qml/GraphEditor/AttributePin.qml
Labels: UI

#2535 [main] Fix imagesFolder variable in order to save when gallery is not empty
  meshroom/ui/qml/main.qml
Labels: bugfix

#2541 [ui] Add View Image Gallery Parameter
  meshroom/ui/qml/Application.qml
  meshroom/ui/qml/Controls/MSplitView.qml
  meshroom/ui/qml/Controls/qmldir
  meshroom/ui/qml/GraphEditor/ChunksListView.qml
  meshroom/ui/qml/GraphEditor/NodeChunks.qml
  meshroom/ui/qml/GraphEditor/NodeEditor.qml
  meshroom/ui/qml/GraphEditor/NodeStatistics.qml
  meshroom/ui/qml/Homepage.qml
  meshroom/ui/qml/Viewer3D/Viewer3D.qml
  meshroom/ui/qml/WorkspaceView.qml
Labels: UI

#2545 Fix homepage SplitViews
  meshroom/ui/img/MIKROS_TG.png
  meshroom/ui/img/MILL_TG.png
  meshroom/ui/img/MPC_TG.png
  meshroom/ui/img/TechnicolorGames_TG.png
  meshroom/ui/qml/Controls/MSplitView.qml
  meshroom/ui/qml/Homepage.qml
  meshroom/ui/qml/MaterialIcons/MaterialToolLabelButton.qml
Labels: bugfix

#2539 Added Pre and Post process functions on the Base Node
  meshroom/core/desc.py
  meshroom/core/node.py
Labels: feature

#2551 [ci] Use GitHub's workflows for the Windows CI instead of appveyor
  .github/workflows/continuous-integration.yml
  .travis.yml
  README.md
  appveyor.yml
Labels: ci

#2552 [core] Check provided template folder exists before attempting to load it
  meshroom/core/__init__.py
Labels: bugfix
