Repository alicevision/Meshroom, pull requests merged in 2024-02, with the labels that each got.

#2280 Update `ListAttributes` identically when removing edges or nodes
  meshroom/core/graph.py
  meshroom/ui/commands.py
Labels: bugfix

#2311 [nodes] CameraInit: check allowedCameraModels validity
  meshroom/nodes/aliceVision/CameraInit.py
Labels: prio:minor

#2324 First node for Lidar Meshing
  meshroom/nodes/aliceVision/LidarMeshing.py
Labels: majorFeature
