Repository alicevision/Meshroom, pull requests merged in 2024-06, with the labels that each got.

#2396 [ui/core] Fix get latest SfM node for previz
  meshroom/core/graph.py
  meshroom/ui/reconstruction.py
Labels: bugfix

#2420 [nodes/ui] Fix ExportAnimatedCamera outputs for ScenePreview use
  meshroom/nodes/aliceVision/ExportAnimatedCamera.py
  meshroom/ui/reconstruction.py
Labels: bugfix

#2419 [fix] Various fixes
  meshroom/core/graph.py
  meshroom/nodes/aliceVision/ImageProcessing.py
  meshroom/ui/components/filepath.py
Labels: bugfix

#2364 New InputNode for nodes without computation and support for all param types in output (and no more limited to File type)
  meshroom/core/attribute.py
  meshroom/core/desc.py
  meshroom/core/node.py
  meshroom/core/taskManager.py
  meshroom/ui/qml/GraphEditor/GraphEditor.qml
  meshroom/ui/qml/GraphEditor/Node.qml
  meshroom/ui/qml/GraphEditor/NodeEditor.qml
  meshroom/ui/qml/Viewer/Viewer2D.qml
  tests/test_compatibility.py
  tests/test_multiviewPipeline.py
Labels: majorFeature

#2425 [ui] RGBA shortcuts for Image Viewer
  meshroom/ui/qml/Viewer/HdrImageToolbar.qml
  meshroom/ui/qml/Viewer/Viewer2D.qml
Labels: feature

#2427 [GraphEditor] Eye on displayable node even if not computed
  meshroom/ui/qml/GraphEditor/Node.qml
Labels: UI

#2430 [ui] Shortcuts in Viewer2D and SequencePlayer
  meshroom/ui/qml/Viewer/SequencePlayer.qml
  meshroom/ui/qml/Viewer/Viewer2D.qml
Labels: feature

#2433 [nodes] Blender scripts: Add missing `__init__.py`
  meshroom/nodes/blender/scripts/__init__.py
Labels: scope:build

#2432 [core] New dynamic output attributes
  meshroom/core/__init__.py
  meshroom/core/attribute.py
  meshroom/core/desc.py
  meshroom/core/graph.py
  meshroom/core/node.py
  meshroom/core/taskManager.py
  meshroom/ui/graph.py
Labels: majorFeature

#2254 [Utils] `getTimeStr`: Round up the number of minutes correctly
  meshroom/ui/qml/Controls/TextFileViewer.qml
  meshroom/ui/qml/GraphEditor/NodeEditor.qml
  meshroom/ui/qml/GraphEditor/NodeStatistics.qml
  meshroom/ui/qml/Utils/format.js
Labels: bugfix

#2375 [core/ui] Load image sequence from node's output in SequencePlayer
  meshroom/__init__.py
  meshroom/core/attribute.py
  meshroom/core/node.py
  meshroom/ui/components/filepath.py
  meshroom/ui/qml/GraphEditor/Node.qml
  meshroom/ui/qml/GraphEditor/NodeEditor.qml
  meshroom/ui/qml/Viewer/SequencePlayer.qml
  meshroom/ui/qml/Viewer/Viewer2D.qml
  requirements.txt
Labels: feature, UI

#2448 Update ripple with "cuda" instead of "gpu"
  meshroom/submitters/rippleSubmitter.py
Labels: prio:minor
