Repository alicevision/Meshroom, pull requests merged in 2024-03, with the labels that each got.

#2335 [nodes] ExportAnimatedCameras: rename as ST maps (instead of UV)
  meshroom/nodes/aliceVision/ExportAnimatedCamera.py
Labels: bugfix

#2337 [nodes] New node MeshRemoveUnseenFaces
  meshroom/nodes/aliceVision/MeshRemoveUnseenFaces.py
Labels: feature

#2349 Upgrade intrinsics for distortion
  meshroom/nodes/aliceVision/CameraInit.py
Labels: bugfix

#2346 Custom loader for .pc.ply pointcloud
  meshroom/ui/qml/Viewer3D/MediaLoader.qml
Labels: feature

#2348 [submitters] Update SimpleFarm configuration tags
  bin/meshroom_batch
  bin/meshroom_submit
  meshroom/submitters/simpleFarmConfig.json
  meshroom/ui/app.py
Labels: submitter
