Repository alicevision/Meshroom, pull requests merged in 2025-01, with the labels that each got.

#2587 [ui] Python Script Editor Improvements
  meshroom/ui/components/__init__.py
  meshroom/ui/components/scriptEditor.py
  meshroom/ui/qml/Application.qml
  meshroom/ui/qml/GraphEditor/ScriptEditor.qml
Labels: majorFeature

#2642 Update sfm pipeline to accept meshes
  meshroom/nodes/aliceVision/ExportMatches.py
  meshroom/nodes/aliceVision/RelativePoseEstimating.py
  meshroom/nodes/aliceVision/SfmBootstraping.py
  meshroom/nodes/aliceVision/SfmExpanding.py
  meshroom/pipelines/nodalCameraTracking.mg
  meshroom/pipelines/nodalCameraTrackingWithoutCalibration.mg
Labels: feature

#2655 [ImageGallery] Intrinsics table: Always fully instantiate the model before populating it
  meshroom/ui/qml/ImageGallery/ImageGallery.qml
  meshroom/ui/qml/ImageGallery/IntrinsicDisplayDelegate.qml
Labels: bugfix

#2652 Enable Fitting of selected Nodes in the Graph Editor when Fit is invoked
  meshroom/ui/qml/GraphEditor/GraphEditor.qml
Labels: feature
