Repository alicevision/Meshroom, pull requests merged in 2025-08, with the labels that each got.

#2787 [doc] Update `INSTALL.md` and `README.md` files
  INSTALL.md
  INSTALL_PLUGINS.md
  README.md
Labels: scope:doc

#2792 [doc] README.md: Add DeepWiki link, the AI documentation you can talk to
  README.md
Labels: feature, scope:doc

#2783 [qml] Minor UI fixes
  meshroom/ui/palette.py
  meshroom/ui/qml/Application.qml
  meshroom/ui/qml/Controls/MessageDialog.qml
  meshroom/ui/qml/GraphEditor/Node.qml
  meshroom/ui/qml/GraphEditor/ScriptEditor.qml
  meshroom/ui/qml/LiveSfmView.qml
  meshroom/ui/qml/main.qml
Labels: UI

#2835 [doc] Update `INSTALL.md`
  INSTALL.md
Labels: scope:doc

#2841 [ci] Remove cloning and setup for `mrSegmentation`
  .github/workflows/continuous-integration.yml
Labels: ci
