Repository alicevision/Meshroom, pull requests merged in 2025-06, with the labels that each got.

#2734 Fix elapsed time when there is only one chunk
  meshroom/core/node.py
Labels: bugfix

#2737 bugfix ExecMode status
  meshroom/core/node.py
Labels: bugfix

#2738 [ui] Update node status when modified
  meshroom/ui/qml/GraphEditor/NodeStatus.qml
Labels: bugfix

#2736 [ui] [fix] MediaLibrary: Check if the model.source is actually an Attribute…
  meshroom/ui/qml/Viewer3D/MediaLibrary.qml
Labels: bugfix, UI

#2741 [ui] [fix] Viewer2D: Failure on MousePosition on some edge cases
  meshroom/ui/qml/Viewer/Viewer2D.qml
Labels: bugfix

#2644 [ui]: Introduction of multiple ways to remove Node Edges
  meshroom/ui/components/edge.py
  meshroom/ui/graph.py
  meshroom/ui/qml/Controls/DelegateSelectionLine.qml
  meshroom/ui/qml/Controls/SelectionLine.qml
  meshroom/ui/qml/Controls/qmldir
  meshroom/ui/qml/GraphEditor/Edge.qml
  meshroom/ui/qml/GraphEditor/GraphEditor.qml
  meshroom/ui/qml/GraphEditor/Node.qml
Labels: UI, majorFeature

#2750 [core] Templates test: Remove outdated `unregisterNodeType` import
  meshroom/core/test.py
Labels: bugfix

#2692 Update to Qt/PySide 6.8.3
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/question_help.md
  INSTALL.md
  dev_requirements.txt
  meshroom/ui/img/MIKROS.png
  meshroom/ui/img/MILL.png
  meshroom/ui/img/MPC.png
  meshroom/ui/img/logo_CTU.png
  meshroom/ui/img/logo_IRIT.png
  meshroom/ui/img/logo_enpc.png
  meshroom/ui/img/logo_uio.png
  meshroom/ui/qml/WorkspaceView.qml
  requirements.txt
Labels: feature

#2747 [core] Runtime-specific environments support
  .git-blame-ignore-revs
  .github/workflows/continuous-integration.yml
  meshroom/core/__init__.py
  meshroom/core/attribute.py
  meshroom/core/desc/node.py
  meshroom/core/graph.py
  meshroom/core/graphIO.py
  meshroom/core/plugins.py
  meshroom/env.py
  tests/conftest.py
  tests/plugins/meshroom/pluginA/PluginANodeA.py
  tests/plugins/meshroom/pluginA/PluginANodeB.py
  tests/plugins/meshroom/pluginB/PluginBNodeA.py
  tests/plugins/meshroom/pluginB/PluginBNodeB.py
  tests/test_attributeChoiceParam.py
  tests/test_attributes.py
  tests/test_compatibility.py
  tests/test_graphIO.py
  tests/test_invalidation.py
  tests/test_listAttribute.py
  tests/test_nodeAttributeChangedCallback.py
  tests/test_nodeCallbacks.py
  tests/test_nodeCommandLineFormatting.py
  tests/test_plugins.py
  tests/utils.py
Labels: majorFeature

#2752 [core] Stop checking for templates in "pipelines" folder
  meshroom/core/__init__.py
Labels: bugfix

#2753 [ui] [fix] Viewer2D: using the keyboard shortcuts (r,g,b,a) break the channelBox combobox
  meshroom/ui/qml/Viewer/HdrImageToolbar.qml
  meshroom/ui/qml/Viewer/Viewer2D.qml
Labels: bugfix, UI

#2758 [ci] Update Python version from 3.9.13 to 3.11
  .github/workflows/continuous-integration.yml
Labels: ci

#2762 [ui] Reconstruction: Fix setup of temporary `CameraInit` nodes
  meshroom/ui/reconstruction.py
Labels: bugfix
