Repository alicevision/Meshroom, pull requests merged in 2025-09, with the labels that each got.

#2853 [build] Package the scripts in `bin` alongside the executables
  .git-blame-ignore-revs
  meshroom/core/desc/node.py
  setup.py
Labels: scope:build

#2866 [tests] Improve unit test coverage for plugins
  tests/plugins/meshroom/config.json
  tests/test_plugins.py
  tests/utils.py
Labels: scope:test

#2871 [Controls] Horizontally center the Color Selector with respect to the tool button
  meshroom/ui/qml/Controls/ColorSelector.qml
Labels: bugfix, UI

#2781 [qml] PhongImageViewer: Various improvements
  meshroom/ui/qml/Controls/DirectionalLightPane.qml
  meshroom/ui/qml/Viewer/Viewer2D.qml
Labels: type:enhancement, review, bugfix

#2891 [ui] Status messages interface
  meshroom/ui/app.py
  meshroom/ui/components/messaging.py
  meshroom/ui/components/statusBar.py
  meshroom/ui/qml/Controls/StatusBar.qml
  meshroom/ui/qml/Controls/StatusMessages.qml
Labels: feature, UI
